# -*- coding: utf-8 -*-
"""funcoesteste.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17I3zkgacEMKRMVsSbx8Jtc4lI7KWm_mj
"""

def tupla(): # tuplas são valores fixos atribuidos a variáveis.
  return(3.14, 9.6)

def retorna2(n1, n2, n3, n4, p1, p2, p3, p4):
  return ((n1*p1 + n2*p2 + n3*p3 + n4*p4) / (p1 + p2 + p3 + p4) ) # aqui foi
  # atribuido ao return uma formula matemática de média ponderada.

def retorna():
  return 100

def somaDosNum(*list): # aqui utilizou-se o ponteiro * para indicar que a
# variável será uma lista.
  print('a soma dos numeros é:', sum(list),'\n') # combinando a função sum()
# ira criar uma lista indeterminada de valores com numeros e somará todos eles.

def MediaAritmetica(n1, n2):
  print(f'a média é: {((n1+n2)/2)}')

def AcimaDoPesoEmedias():
  mensagens = [
        "Digite o 1º valor: ",
        "Digite o 2º valor: ",
        "Digite o 3º valor: ",
        "Digite o 4º valor: ",
        "Digite o 5º valor: ",
        "Digite o 6º valor: ",
        "Digite o 7º valor: "
    ]
  Maior90 = 0
  cont = 0
  MediaPesos = []
  for cont in range(7):
        valor = float(input(mensagens[cont]))
        MediaPesos.append(valor)
        if valor > 90:
          Maior90 += 1
  MediaPesos = (sum(MediaPesos)/len(MediaPesos))
  print(f'media dos pesos é: {round(MediaPesos, 29100)} ')
  return print('pessoas acima do peso:', Maior90)

